# Generated by Django 4.2.20 on 2025-04-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomemory',
            name='title',
            field=models.CharField(default='Audio Memory', max_length=255),
        ),
    ]
