# Generated by Django 4.2.20 on 2025-05-01 07:52

import audio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0002_audiomemory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomemory',
            name='title',
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiomemory',
            name='audio_file',
            field=models.FileField(upload_to=audio.models.user_audio_path),
        ),
        migrations.AlterField(
            model_name='audiomemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
