# Generated by Django 4.2.20 on 2025-05-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audiomemory_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomemory',
            name='location_indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='memory_references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='potential_concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='routine_references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='severity_indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomemory',
            name='time_indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiomemory',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
