# Generated by Django 4.2.20 on 2025-05-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audiomemory_location_indicators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiomemory',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
