# Generated by Django 4.2.20 on 2025-05-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('audio', '0005_rename_created_at_audiomemory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
