# Generated by Django 4.2.20 on 2025-04-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reminders', '0002_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='description',
            field=models.CharField(default='No description provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
