# Generated by Django 4.2.20 on 2025-04-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_wallpaper_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
